# Generated by Django 2.2 on 2020-07-10 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Powerbase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Zhibie', models.CharField(choices=[('zhi_1', '一值'), ('zhi_2', '二值'), ('zhi_3', '三值'), ('zhi_4', '四值'), ('zhi_5', '五值')], max_length=10, verbose_name='值别')),
                ('Leiji', models.CharField(choices=[('xiaye', '下夜'), ('zaoban', '早班'), ('zhongban', '中班'), ('shangye', '上夜')], max_length=10, verbose_name='倒班累计')),
                ('Alternator1', models.FloatField(max_length=20, verbose_name='#1发电机')),
                ('Magnification', models.FloatField(default='', max_length=20, verbose_name='倍率')),
                ('Backstagenumber', models.FloatField(default='', max_length=20, verbose_name='电能量后台编号')),
                ('Main1', models.FloatField(max_length=20, verbose_name='#1主变')),
                ('High1', models.FloatField(max_length=20, verbose_name='#1高厂变')),
                ('Desulphurization1', models.FloatField(max_length=20, verbose_name='#1脱硫变')),
                ('Alternator2', models.FloatField(max_length=20, verbose_name='#2发电机')),
                ('Main2', models.FloatField(max_length=20, verbose_name='#2主变')),
                ('High2', models.FloatField(max_length=20, verbose_name='#2高厂变')),
                ('Desulphurization2', models.FloatField(max_length=20, verbose_name='#2脱硫变')),
                ('Start', models.FloatField(max_length=20, verbose_name='启备变')),
                ('FactoryA', models.FloatField(max_length=20, verbose_name='厂前区变A')),
                ('FactoryB', models.FloatField(max_length=20, verbose_name='厂前区变B')),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
            ],
        ),
        migrations.CreateModel(
            name='Powerconsumptionrate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Poweruse1', models.FloatField(max_length=20, verbose_name='#1机厂用电率')),
                ('Poweruse2', models.FloatField(max_length=20, verbose_name='#2机厂用电率')),
                ('Poweruse_all', models.FloatField(max_length=20, verbose_name='全厂用电率')),
                ('Comprehensive1', models.FloatField(max_length=20, verbose_name='#1机综合厂用电率')),
                ('Comprehensive2', models.FloatField(max_length=20, verbose_name='#2机综合厂用电率')),
                ('Comprehensive_all', models.FloatField(max_length=20, verbose_name='全厂综合厂用电率')),
                ('Load1', models.FloatField(max_length=20, verbose_name='#1机发电负荷率')),
                ('Load2', models.FloatField(max_length=20, verbose_name='#2机发电负荷率')),
                ('Load_all', models.FloatField(max_length=20, verbose_name='全场发电负荷率')),
                ('Powergeneration1', models.FloatField(max_length=20, verbose_name='#1机发电量')),
                ('Powermain1', models.FloatField(max_length=20, verbose_name='#1机主变电量')),
                ('Powerhigh1', models.FloatField(max_length=20, verbose_name='#1高厂变电量')),
                ('Powerdesulphurization1', models.FloatField(max_length=20, verbose_name='#1机脱硫电量')),
                ('Powergeneration2', models.FloatField(max_length=20, verbose_name='#2机发电量')),
                ('Powermain2', models.FloatField(max_length=20, verbose_name='#2机主变电量')),
                ('Powerhigh2', models.FloatField(max_length=20, verbose_name='#2高厂变电量')),
                ('Powerdesulphurization2', models.FloatField(max_length=20, verbose_name='#2机脱硫电量')),
                ('Ongridenergy1', models.FloatField(max_length=20, verbose_name='#1机上网电量')),
                ('PowerMachineryFactory1', models.FloatField(max_length=20, verbose_name='#1机厂用电量')),
                ('Ongridenergy2', models.FloatField(max_length=20, verbose_name='#2机上网电量')),
                ('PowerMachineryFactory2', models.FloatField(max_length=20, verbose_name='#2机厂用电量')),
                ('Standbysubstation', models.FloatField(max_length=20, verbose_name='#启备变电量')),
                ('Ongridenergy_all', models.FloatField(max_length=20, verbose_name='#总上网电量')),
                ('PowerMachineryFactory_all', models.FloatField(max_length=20, verbose_name='总厂用电量')),
                ('Powergeneration_all', models.FloatField(max_length=20, verbose_name='总发电量')),
                ('Powermain_all', models.FloatField(max_length=20, verbose_name='总主变电量')),
                ('Powerdesulphurization_all', models.FloatField(max_length=20, verbose_name='总脱硫耗电量')),
                ('Desulfurizationdesulphurization1', models.FloatField(max_length=20, verbose_name='#1机脱硫电耗')),
                ('Desulfurizationdesulphurization2', models.FloatField(max_length=20, verbose_name='#2机脱硫电耗')),
                ('Desulfurizationdesulphurization_all', models.FloatField(max_length=20, verbose_name='总脱硫电耗')),
                ('PowerFactoryA', models.FloatField(max_length=20, verbose_name='A厂前区变电量')),
                ('PowerFactoryB', models.FloatField(max_length=20, verbose_name='B厂前区变电量')),
                ('PowerFactory_all', models.FloatField(max_length=20, verbose_name='厂前区变电量')),
                ('Powerwater', models.FloatField(max_length=20, verbose_name='全厂制水电耗')),
            ],
        ),
    ]
